name: Build YummyAdmin
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # (اختياري) ضبط المسار الفرعي /yummyadmin/
      - name: Patch Vite base path
        run: |
          if grep -q "defineConfig(" vite.config.ts; then
            sed -i 's|defineConfig({|defineConfig({ base: "/yummyadmin/",|' vite.config.ts
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: yummyadmin-dist
          path: dist
