name: Build YummyAdmin
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # (اختياري) لو بتخدم تحت /yummyadmin داخل Laravel
      - name: Patch Vite base path
        run: |
          if [ -f "vite.config.ts" ]; then
            sed -i 's|defineConfig({|defineConfig({ base: "/yummyadmin/",|' vite.config.ts || true
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'           # هذا فقط للتخزين المؤقت، لا يعتمد على lock

      # المهم: لا تستخدم npm ci
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: yummyadmin-dist
          path: dist
